import Head from 'next/head'
import { Container, Heading } from "@chakra-ui/react"
import Footer from '../components/footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Raypath Infinity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="container.lg">
        <Heading as="h1" size="2xl" lineHeight="1.2" isTruncated>Raypath Infinity</Heading>
      </Container>
      <Footer />
    </div>
  )
}