import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Raypath Infinity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <header className={styles.header}>
          <Image src="/raypath-logo.svg" alt="Vercel Logo" width={350} height={85} />
        </header> */}
        <a
          href="/"
        >
            wróć
        </a>
        <h1 className={styles.title}>
          Tychy
        </h1>

        <p className={styles.description}>
          Wypełnij formularz
        </p>

        <div className={styles.grid}>
          <a href="/tychy" className={styles.card}>
            <h2>Tychy &rarr;</h2>
            <p>Al. Niepodległości 106</p>
            <p>43-100 Tychy</p>
          </a>

          <a href="/warszawa" className={styles.card}>
            <h2>Kraków &rarr;</h2>
            <p>Nad Potokiem 7a</p>
            <p>30-199 Kraków, Rząska</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://marcinzogrodnik.pl"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image src="/mz.svg" alt="Vercel Logo" width={50} height={25} />
          </span>
        </a>
      </footer>
    </div>
  )
}
